server:
  port: 80
  
spring:
  application:
    name: crowd-zuul-Gateway
  
  redis:
    host: 192.168.3.170
  session:
    store-type: redis   
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
    # 配置使用指定IP
    ip-address: 127.0.0.1
  
zuul:
  ignored-services: "*"   #表示禁用默认路由，只认我们自己配置的路由. 
  sensitive-headers: "*"  # 在 Zuul 向其他微服务重定向时保持原本头信息（请求头、响应头） 
  routes:
    crowd-portal: 
     service-id: crowd-auth 
     path: /**          # 这里一定要使用两个“*”号，不然“/”路径后面的多层路径将无法访问  
    crowd-project: 
      service-id: crowd-project-consumer
      path: /project/**
    crowd-order: 
      service-id: crowd-project-order
      path: /order/** 
    crowd-pay: 
      service-id: crowd-project-pay
      path: /pay/** 
    
    
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000   